- bin/docserv
This one is probably not yet in a mergeable state but I'd actually appreciate if you carried it down the road, @svenseeberg. :/
I tried to (partially) address #31 here and also tried to simplify the format I suggested in #18. I have also added a bunch of information that is relevant to me but that so far was not part of the cache file.
However, I have not tried this (because blank readme winkwinknudgenudge). I am not sure whether any of the XPaths we use for selecting the title is broken.
The following is the file format I was shooting for in this PR:
```
<document productid="sled" setid="15ga" lang="en-us" dc="DC-SLES-all" cachedate="123954857">
<commit>faabbaaf</commit>
<path format="pdf">en-us/sles/15ga/book.security/book.security_color_en.pdf</path>
<title rootid="">SLES …
```
> Improve file format for document cache files

- bin/docserv
- config/docserv.ini
* Add the config entry 'internal=' which sets the
--internal-mode parameter for docserv-buildoverview
* Fixes #32
> Add internal mode

- bin/docserv
* The subdir element is added to the path of the
temporary git repository clone. This is then used
as the source for the daps2docker run.
> Add subdir handling

- bin/docserv
* Use paths defined in environment variables. The
variables can be set with the 'dev-mode.sh'.
* Fix #44
> Add dev mode to docserv

- src/docserv/bih.py
- src/docserv/deliverable.py
- src/docserv/docserv.py
- src/docserv/functions.py
- src/docserv/repolock.py
- src/docserv/rest.py
Don't evaluate the string, delegate it to the logger module. Especially for bigger objects, this makes it a little bit more performant as logging strings are only evaluated when they are needed.
Basically, this:
```python
logger.info("Person: %s" % "Tux")
```
is replaced by this (see the comma):
```python
logger.info("Person: %s", "Tux")
```
> Improve logging call

- bin/docserv-createconfig
This PR contains:
* when pygit2 is missing, the script uses `-h`/`--help` correctly. 
* uses the argparse module to parse the command line
* prints the path to the config file
> Fix #67 to avoid traceback

- config/config.d/sample_product.xml
- share/schema/config-validation.rnc
- share/xslt/positive-config.xsl
- src/docserv/bih.py
- src/docserv/deliverable.py
This PR fixes #107 and contains the following changes:
* Add `<dl>` as HTML element to the `ds.htmlblock`
* Create separate patterns for "1" | "true" and "0" | "false"
* Enhance `<a>` with "target" attribute
* Add "global" `<git>` element under `<product>` and make `<git>` under `<builddocs>` optional
Questions to @sknorr 
* Should the `target` attribute just be `text` instead of this list with these `_blank` etc. entries?
* Is it ok to change the `<git>` element to optional under `<product>` *and* `<builddocs>`?
(I guess, we need to tackle the situation that there is no `<git>` element in the validation script)
> WIP: Improvements for config-validation.rnc

- bin/docserv-createconfig
We need it to collect **all** DC files.
> Fix #129: collect all DC files

- src/docserv/deliverable.py
We try to be clever and avoid rebuilds if the documents should be
up-to-date. However, there is a few important conditions that we
don't check for:
* Do we have any old documents that need to be cleaned up? (Since
86fd3669 we are always cleaning up all documents of the current
docset)
* Has the container been updated to fix an issue with the output?
* The current system also does not work properly with how the ZIP
builder is integrated (because we build a perfect directory of
documents into /tmp and only want to copy that to the builds dir
if the docset is still supported, otherwise we should only copy the
ZIP file).
So, for the moment, let's skip that whole cleverness altogether,
admit defeat and REBUILD ALL THE THINGS!
> ds2: Don't skip build when document is supposedly up-to-date (#195)

- share/build-navigation/web-resources/docservui.js
Selecting Language does not work in Chromium
Moved the addEventListener for language changes out of the for loop and made
it work on the <select> element ather than on the options. Also, the event now
listens for "change" rather than "click"
> Fix for issue #222

- bin/docserv-build-navigation
- src/docserv/bih.py
This is untested currently. But it's a fairly small change.
----
@tomschr To get a full fix, I'd love to have a look at the error message that you originally got in the context of failing to build `sles/15-SP3/en`. Could you check if you still have this txt file that was indicated in the output you put into pastebin? `~/repos/GL/susedoc/docserv-config/0cache/docserv-message-2021-07-06T11:33:36+02:00-90pifueu.txt`
> bih: Cancel BIs with non-existing languages early on (#262)

- bin/docserv-build-navigation
- docs/adoc/config-product.adoc
- share/build-navigation/list-related-products.xsl
~100% untested but I have high hopes~
Tested now, and after two small fixes, it works. However, there are some pretty large logical gaps here:
* The current code works for updating dependent pages that are referenced from the page of the original docset (i.e. the docset we actively intended to rebuild) by means of a \<ref/\>.
* The current code may remove (still-working) refs from dependent pages if the refs (or underlying documents) have been removed from the newest version of the product config. That may or may not be what you want, but that's probably not a huge issue.
* It has a complete blind spot when it comes to removing historical refs that still exist in the rendered page but no longer in the product config, pointing at the original docset. I could imagine remediating that issue …
> build-nav: Rebuild dependent pages

- src/docserv/bih.py
- src/docserv/deliverable.py
- versionbump
This PR contains:
* Use echo before `rm -rf` for temp dirs/files
* Delete temp dirs and directories with systemd's systemd-tmpfiles-clean
> Keep temorary dirs/files for debugging reasons

- src/docserv/bih.py
* re-enabling deletion of the target directory Makes sure no unused files remain in $backup_path
* copying the zip archive for unsupported products to $backup_path This fixes an error, it was missing
> Two fixes for copying deliverables to $backup_path

- bin/docserv-stitch
- share/validate-product-config/product-config-schema.rnc
Use it inside <docset> like this:
```xml
<docset lifecycle="supported" setid="12-SP4">
<version>12 SP4</version>
<canonical>sles/12-SP5</canonical>
</docset>
```
> Add optional <canonical> tag

- share/validate-product-config/product-config-schema.rnc
The `<title>` tag inside `<desc>` is used for tiles and a restricted currently to 70 characters.
@fsundermeyer We didn't discuss this in our last doc tools meeting, but I'd like to merge it. Any objections from your part?
This is how it looks like:
```xml
<desc default="1" lang="en-us">
<title>Short description</title>
<p>... longer description ...</p>
</desc>
```
Likewise for other languages.
> Introduce <desc> with <title>

- share/validate-product-config/product-config-schema.rnc
This PR adds the element `<partners>` to `<deliverable>`. It is only useful for the `trd.xml` config file.
You can write now:
```xml
<deliverable titleformat="title product" category="...">
<subdir>a/b</subdir>
<dc>DC-...</dc>
<format html="1" pdf="1" single-html="1"/>
<partners>
<partner>Vendor</partner>
</partners>
</deliverable>
```
> For TRD, allow optional partners inside deliverable

- bin/docserv-stitch
- src/docserv/bih.py
- src/docserv/docserv.py
The script created an arbitrary directory at `/tmp/docserv-stitch-tempdir-XXX`. It's changed now:
- The arbitrary directory is gone.
- We use `/tmp/docserv-stitch-tempdir-$DATE`
- DATE is of format "YYY-MM-DD"
> Create consistent temp directory

- share/validate-product-config/product-config-schema.rnc
The Docserv config allows the "gated" attribute (type boolean) on these elements:
* `<product>`
* `<docset>`
* `<deliverable>`
* `<link>`
By default, it's set to `gated="false"` (= publicly available).
The idea to have it on these different levels is flexibility and readability. You can have a product and set everything as `gated="true"`, but still have a few deliverables that are publicly available.
> Support "gated" attribute in product config schema

- share/validate-product-config/product-config-schema.rnc
These patterns are created:
* `ds.href.attr`
* `ds.draft.attr`
* `ds.remarks.attr`
* `ds.meta.attr`
* `ds.lang.attr`
* `ds.includes-productname.attr`
* `ds.category.attr`
* `ds.title.attr`
* `ds.titleformat.attr`
* `ds.default.{true,false}.attr`
> Refactor RNC: Introduce patterns for common attributes

- share/validate-product-config/product-config-schema.rnc
Due to DOCTEAM-1723, we need to outsource the categories into a separate file. That file needs to be included in all Docserv configs.
This change contains:
* Allows to `xi:includes` elements at the same place where a `<category>` element is allowed
* Introduces the wrapper element `<categories>` (plural!)
* Allows `<categories>` as root element (for the separate file which contains all categories)
> Change product schema to include XInclude
